Redis 7.0.11
unikraft/lib-redis pull request #10
Opened 2023-06-05 13:19 UTC by John-Ted

Update `redis` to 7.0.11

This library was built using `musl`, some patches are not compatible with `pthread-embedded`.

2023-07-18 15:08 UTC, StefanJum requested changes
Thank you @John-Ted.

Some other things besides the comments:
* Update the commit messages and add short descriptions when needed (e.g. explain what new source files were added, explain what patcher were added, explain why `histogram` was added as a dependency).
* Sign-off the commits with the same email you added in the `Makefile.uk` `authors`.
* Check that everything that is moved from `LIBREDIS_SERVER` to `LIBREDIS_COMMON` makes sense to be moved there. `LIBREDIS_COMMON` should be a list of everything that is needed **both** by the server and the client, and it should be minimal.

2023-07-18 15:08 UTC, StefanJum commented on patches/0001-deps-hiredis-Remove-unused-dependency-to-tcp.patch
> ++#include <netinet/tcp.h>
Looks like this patch does not do anything right?

2023-07-18 15:08 UTC, StefanJum commented on patches/0004-src-Change-header-path-to-relative.patch
> ++#include "../deps/hdr_histogram/hdr_histogram.h"
This is not needed, the path is added in the `CINCLUDES` in the `Makefile.uk`.

2023-07-18 15:08 UTC, StefanJum commented on patches/0006-src-Change-name-of-server-main-to-avoid-clash.patch
> ++int redis_server_main(int argc, char **argv) {
We can do this by using `-Dmain=redis_server_main`, like it's done in other libraries (e.g. [sqlite](https://github.com/unikraft/lib-sqlite/blob/staging/Makefile.uk#L84)).

2023-07-18 15:08 UTC, StefanJum commented on patches/0007-src-Ensure-compatibility-with-pthread-embedded.patch
> ++        if (bio_threads[j] && pthread_cancel(bio_threads[j]) == 0) {
This looks like it's not needed

2023-07-18 15:08 UTC, StefanJum commented on patches/0007-src-Ensure-compatibility-with-pthread-embedded.patch
> ++    if (pthread_self() != server.main_thread_id && pthread_cancel(server.main_thread_id) == 0) {
Also looks not needed.

2023-07-18 15:08 UTC, StefanJum commented on patches/0007-src-Ensure-compatibility-with-pthread-embedded.patch
> ++        if (io_threads[j] && pthread_cancel(io_threads[j]) == 0) {
Also looks not needed.

2023-07-18 15:08 UTC, StefanJum commented on patches/0007-src-Ensure-compatibility-with-pthread-embedded.patch
> ++                        (unsigned long)io_threads[j], strerror(err));
Also looks not needed.

2023-07-18 15:08 UTC, StefanJum commented on patches/0007-src-Ensure-compatibility-with-pthread-embedded.patch
> ++                    "IO thread(tid:%lu) terminated",(unsigned long)io_threads[j]);
Also looks not needed.

2023-07-18 15:08 UTC, StefanJum commented on patches/0010-remove-unnecessary-header.patch
> +diff --git a/src/replication.c b/src/replication.c
Use git patches, with a commit message and a sign-off tag, similar to other patches in this pr.

2023-07-18 15:08 UTC, StefanJum commented on patches/0006-src-Change-name-of-server-main-to-avoid-clash.patch
> ++int redis_server_main(int argc, char **argv) {
Use the same logic that is used on the `REDIS_CLIENT` main function in the `Makefile.uk`.

2023-07-18 15:08 UTC, StefanJum commented on Makefile.uk
> +LIBREDIS_COMMON_SRCS-y += $(LIBREDIS_SRC)/server.c
```suggestion
LIBREDIS_SERVER_SRCS-y += $(LIBREDIS_SRC)/server.c
```
Move this to the `redis_server` internal library

2023-07-18 15:08 UTC, StefanJum commented on Makefile.uk
> +LIBREDIS_COMMON_SRCS-y += $(LIBREDIS_SRC)/server.c
Also add a `-Dmain=redis_server_main` flag.

2023-07-18 15:08 UTC, StefanJum commented on Makefile.uk
> +LIBREDIS_COMMON_SRCS-y += $(LIBREDIS_SRC)/sds.c
Any reason all these files were moved from `LIBREDIS_SERVER` to `LIBREDIS_COMMON`?
Do we need them if compiling for `Redis Client`?

2023-07-21 14:14 UTC, RaduNichita reviewed
At least on my side, there seem to be a problem with timestamps.

For `aarch64`, the timestamp appear to be `-748823 Jan 1970 -19:-36:00.145`, whereas for `qemux86_64` it appears to be `28 Jul 2015 07:49:05.074`

@John-Ted do you have any idea why this may be happening?

Otherwise, I have been able to test and the things seems fine. :100:

2023-07-21 14:14 UTC, RaduNichita commented on patches/0010-remove-unnecessary-header.patch
> ++// #include <memory.h>
Why do we have this as a comment?

2023-07-30 10:19 UTC, John-Ted commented
In regards to the timestamps, on ARM the `gettimeofday` call does not function properly. On x86, I tracked it down to this [1], which calls their version of `localtime` with the `server.timezone` parameter, which is subtracted from the timestamp [2]. This variable has the value `263675520`, which corresponds to a shift of about 8 years, consistent with the change from 2023 to 2015.

[1]: https://github.com/redis/redis/blob/6abb3c40384bd507fe410680e0e0fefc4141f8a3/src/server.c#L130
[2]: https://github.com/redis/redis/blob/6abb3c40384bd507fe410680e0e0fefc4141f8a3/src/localtime.c#L64

2023-07-30 10:41 UTC, StefanJum requested changes
Works great @John-Ted, thank you.
Please start your commit messages with a capital letter.
Also see the changes to the commits below:

* `bump version to 7.0.11` -> `Bump version from ---- to 7.0.11`
    Add a description of what changes needed to be made, new dependencies, new patches, etc.
* ` refactor code into single library` -> `Makefile.uk: Refactor code into single library`
    Also add a description here, state that previously there were separate libraries for 
    `LIBREDIS_SERVER`, `LIBREDIS_CLIENT`, `LIBREDIS_COMMON`, now we do the separation
     by config options.
* `improve patches` -> `patches: Impove patches`
    Also, I would only leave this to remove the unnecessary patches, and update patch 6 in
    the [commit that adds it](https://github.com/unikraft/lib-redis/pull/10/commits/3af42dec29a227c1d04e574213141b2f5a453a41#diff-16cc4d4e70abccd687ecc3a8e39fe0438f43100cd2625b0de2184f4298553f11).
    So in the end the commit would be `patches: Remove unnecesarry patches`.

2023-07-30 11:56 UTC, StefanJum requested changes
@John-Ted should [this commit](https://github.com/unikraft/lib-redis/pull/10/commits/4e4c62080d455b786a7d5d8cc62864fff491c489) be part of [this one](https://github.com/unikraft/lib-redis/pull/10/commits/0257073abded2f935f72b0fbab76c516a2d81a89)? We should try to keep it as `bisect-friendly` as possible, ideally if you check out on any of the commits the library should compile fine.

2023-07-30 12:04 UTC, RaduNichita requested changes
For the commit 1b46aa5717b8bcc3015e1df620f7cc1113b07f37 ( patches: Remove unnecessary patches) , please state why these patches are not necessarry anymore.

2023-07-30 13:11 UTC, StefanJum reviewed
Looks fine to me besides the one comment @John-Ted, I'll wait for @RaduNichita to also test on his side.

2023-07-30 13:11 UTC, StefanJum commented on Makefile.uk
> +LIBREDIS_SRCS-y += $(LIBREDIS_SRC)/adlist.c
Please order the `LIBREDIS_SRCS` source files in lexicographic order.

2023-07-30 13:31 UTC, StefanJum approved these changes
All good on my side, thank you. I'll add the tag after @RaduNichita is happy.

2023-07-30 13:57 UTC, RaduNichita approved these changes
All good with me now. I am happy! 

Reviwed-by: Radu Nichita <radunichita99@gmail.com>

2023-07-30 13:58 UTC, StefanJum approved these changes
Approved-by: Stefan Jumarea <stefanjumarea02@gmail.com>

2023-08-04 10:09 UTC, closed without merging